sudo: enabled
cache:
    - yarn
    - pip
install:
    - sudo apt-get update
    - sudo apt-get install nodejs npm python-pip

    - sudo pip install --upgrade pip
    - npm i -g npm

    - sudo pip install git-lint
    - npm install -g yarn webpack webpack-cli eslint eslint-plugin-react lint-diff
    - sudo pip install -r dev_reqs.txt
    - yarn install
script:
    - if [[ $TRAVIS_COMMIT_MESSAGE != *"bundle for production"* ]]; then lint-diff $TRAVIS_COMMIT_RANGE ; fi ;
    - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint
    - yarn test
    - sudo env/bin/python variora/manage.py test variora/ --pattern="tests.py"
