sudo: enabled
cache:
  - yarn
  - pip
install:
  - sudo apt-get update
  - sudo apt-get install nodejs npm python-pip

  - sudo source setupdev.sh

  - sudo pip install git-lint
  - npm install -g eslint eslint-plugin-react lint-diff
script:
  - lint-diff $TRAVIS_COMMIT_RANGE
  - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint
  - npm test
