sudo: enabled
install:
  - sudo apt-get update
  - sudo apt-get install nodejs npm python-pip

  - sudo pip install --upgrade pip
  - npm i -g npm

  - sudo pip install -r dev_reqs.txt
  - sudo pip install git-lint
  - npm install -g yarn webpack eslint eslint-plugin-react lint-diff
  - yarn install
script:
  - lint-diff $TRAVIS_COMMIT_RANGE
  - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint
  - npm test
