sudo: enabled
install:
  - sudo apt-get update
  - sudo apt-get install nodejs npm python-pip
  - sudo pip install --upgrade pip
  - sudo pip install -r prod_reqs.txt
  - npm install
  - npm install -g webpack jest
script:
  - npm test
