sudo: enabled
cache:
    - yarn
    - pip
install:
    - sudo apt-get update
    - sudo apt-get install nodejs npm python-pip
    - node -v

    - sudo pip install --upgrade pip
    - npm i -g npm

    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
    - command -v nvm
    - nvm ls
    - nvm install v8.16.0
    - nvm use v8.16.0

    - sudo pip install git-lint
    - npm install -g yarn webpack webpack-cli eslint eslint-plugin-react lint-diff
    - sudo pip install -r dev_reqs.txt
    - yarn install
script:
    - if [[ $TRAVIS_COMMIT_MESSAGE != *"bundle for production"* ]]; then lint-diff $TRAVIS_COMMIT_RANGE ; fi ;
    - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint
    - yarn test
