sudo: enabled
install:
  - sudo apt-get update
  - sudo apt-get install nodejs npm python-pip

  - sudo pip install --upgrade pip
  - npm i -g npm

  - sudo pip install -r prod_reqs.txt
  - yarn install
  - npm install -g webpack eslint lint-diff
script:
  - lint-diff $TRAVIS_COMMIT_RANGE
  - npm test
