# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-01-23 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunnylol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunnylolcommand',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
